server:
  port: 8081

spring:
  application:
    name: To-Do-App

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog.xml

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/todo-realm
        jwk-set-uri: http://localhost:8080/realms/todo-realm/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true